[package]
name = "lpa"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
csv = "1.1.6"
clap = "3.0.0-beta.4"
#clap_derive = "=3.0.0-beta.2"
rand = "0.8"
